anime:
    domain_name: 'anime.%domain_name%'
    base_folder: '%env(ANIME_BASE_FOLDER)%'
    temp_folder: '%env(ANIME_TEMP_FOLDER)%'
    myanimelist:
        url: 'https://myanimelist.net'
        api_url: 'https://api.myanimelist.net'
        client_id: '%env(MAL_CLIENT_ID)%'
        client_secret: '%env(MAL_CLIENT_SECRET)%'
    anilist:
        url: 'https://anilist.co'
        api_url: 'https://graphql.anilist.co'
        client_id: '%env(AL_CLIENT_ID)%'
        client_secret: '%env(AL_CLIENT_SECRET)%'
    animeworld:
        url_regex: '/^https:\/\/www\.animeworld\.(ac|so)\/.*/'
        url: 'https://www.animeworld.ac'
        api_url: 'https://api.animeworld.ac'
        client_id: '%env(AW_CLIENT_ID)%'
        api_key: '%env(AW_API_KEY)%'
    animeunity:
        url_regex: '/^https:\/\/www\.animeunity\.(to|so)\/.*/'
        url: 'https://www.animeunity.so'
    youtube_dl:
        bin_path: '%env(YOUTUBE_DL_BIN_PATH)%'
