anime:
    domain_name: 'anime.%domain_name%'
    base_folder: '%env(ANIME_BASE_FOLDER)%'
    temp_folder: '%env(ANIME_TEMP_FOLDER)%'
    myanimelist:
        url: 'https://api.myanimelist.net'
        client_id: '%env(MAL_CLIENT_ID)%'
        client_secret: '%env(MAL_CLIENT_SECRET)%'
    anilist:
        url: 'https://graphql.anilist.co'
        client_id: '%env(AL_CLIENT_ID)%'
        client_secret: '%env(AL_CLIENT_SECRET)%'
    animeworld:
        url: 'https://www.animeworld.so'
        api_url: 'https://api.animeworld.so'
        client_id: '%env(AW_CLIENT_ID)%'
        api_key: '%env(AW_API_KEY)%'
    animeunity:
        url: 'https://www.animeunity.to'
    youtube_dl:
        bin_path: '%env(YOUTUBE_DL_BIN_PATH)%'
