anime:
    domain_name: 'anime.%domain_name%'
    base_folder: '%env(ANIME_BASE_FOLDER)%'
    temp_folder: '%env(ANIME_TEMP_FOLDER)%'
    download_extension: '%env(ANIME_DOWNLOAD_EXTENSION)%'
    myanimelist:
        url: 'https://api.myanimelist.net'
        client_id: '%env(MAL_CLIENT_ID)%'
        client_secret: '%env(MAL_CLIENT_SECRET)%'
    animeworld:
        url: 'https://www.animeworld.so'
        api_url: 'https://api.animeworld.so'
        client_id: '%env(AW_CLIENT_ID)%'
        api_key: '%env(AW_API_KEY)%'
    animeunity:
        url: 'https://www.animeunity.to'
    youtube_dl:
        path: '%env(YOUTUBE_DL_PATH)%'

twig:
    globals:
        anime_domain_name: '%anime.domain_name%'

doctrine:
    orm:
        mappings:
            App\AnimeBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/AnimeBundle/src/Entity'
                prefix: 'App\AnimeBundle\Entity'
                alias: AnimeBundle

framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            anime_episode_download_failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=anime_episode_download_failed'
            anime_episode_download:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: anime_episode_download_failed
                options:
                    queue_name: anime_episode_download
                retry_strategy:
                    max_retries: 3
                    delay: 60000
                    multiplier: 3
        routing:
            App\AnimeBundle\Message\EpisodeDownloadNotification: anime_episode_download
            App\AnimeBundle\Message\AnimeCacheRefreshNotification: core_async
            App\AnimeBundle\Message\MangaCacheRefreshNotification: core_async
    http_client:
        scoped_clients:
            anime.myanimelist.client:
                base_uri: '%anime.myanimelist.url%'
                headers:
                    X-MAL-CLIENT-ID: '%anime.myanimelist.client_id%'
            anime.animeworld.client:
                base_uri: '%anime.animeworld.url%'