books:
    domain_name: 'books.%domain_name%'

twig:
    globals:
        books_domain_name: '%books.domain_name%'

doctrine:
    orm:
        mappings:
            App\BooksBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/BooksBundle/src/Entity'
                prefix: 'App\BooksBundle\Entity'
                alias: BooksBundle

security:
    role_hierarchy:
        ROLE_ADMIN_BOOKS: [ROLE_USER_BOOKS]

liip_imagine:
    filter_sets:
        books_thumb:
            data_loader: books.book_cover_loader
            format: webp
            quality: 75
            filters:
                thumbnail:
                    size: [300, 450]
                    mode: inset
                    allow_upscale: false
        books_cover:
            data_loader: books.book_cover_loader
            format: webp
            quality: 80
            filters:
                thumbnail:
                    size: [600, 900]
                    mode: inset
                    allow_upscale: false