books:
    domain_name: 'books.%domain_name%'
    base_folder: '%env(BOOKS_BASE_FOLDER)%'
    covers_folder: '%env(BOOKS_COVERS_FOLDER)%'

twig:
    globals:
        books_domain_name: '%books.domain_name%'

doctrine:
    orm:
        mappings:
            App\BooksBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/BooksBundle/src/Entity'
                prefix: 'App\BooksBundle\Entity'
                alias: BooksBundle

liip_imagine:
    filter_sets:
        books_thumb:
            data_loader: books_covers_folder
            format: webp
            quality: 75
            filters:
                thumbnail:
                    size: [300, 450]
                    mode: inset
                    allow_upscale: false
        books_cover:
            data_loader: books_covers_folder
            format: webp
            quality: 80
            filters:
                thumbnail:
                    size: [600, 900]
                    mode: inset
                    allow_upscale: false
    loaders:
        books_covers_folder:
            filesystem:
                data_root: '%env(BOOKS_COVERS_FOLDER)%'