books:
    domain_name: 'books.%domain_name%'
    base_folder: '%env(BOOKS_BASE_FOLDER)%'
    covers_folder: '%env(BOOKS_COVERS_FOLDER)%'

twig:
    globals:
        books_domain_name: '%books.domain_name%'
