core:

twig:
    paths:
        src/CoreBundle/templates: 'CoreBundle'

doctrine:
    orm:
        mappings:
            App\CoreBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/CoreBundle/src/Entity'
                prefix: 'App\CoreBundle\Entity'
                alias: CoreBundle