doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        #profiling_collect_backtrace: '%kernel.debug%'
        connections:
            core:
                url: '%env(resolve:CORE_DATABASE_URL)%'
            anime:
                url: '%env(resolve:ANIME_DATABASE_URL)%'
            books:
                url: '%env(resolve:BOOKS_DATABASE_URL)%'
        default_connection: core
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        #report_fields_where_declared: true
        #validate_xml_mapping: true
        #naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        #auto_mapping: true
        #mappings:
        #    App:
        #        type: attribute
        #        is_bundle: false
        #        dir: '%kernel.project_dir%/src/Entity'
        #        prefix: 'App\Entity'
        #        alias: App
        default_entity_manager: core
        entity_managers:
            core:
                connection: core
                mappings:
                    App\CoreBundle:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/CoreBundle/src/Entity'
                        prefix: 'App\CoreBundle\Entity'
                        alias: CoreBundle
            anime:
                connection: anime
                mappings:
                    App\AnimeBundle:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/AnimeBundle/src/Entity'
                        prefix: 'App\AnimeBundle\Entity'
                        alias: AnimeBundle
            books:
                connection: books
                mappings:
                    App\BooksBundle:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BooksBundle/src/Entity'
                        prefix: 'App\BooksBundle\Entity'
                        alias: BooksBundle

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
