# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_domain: valdi.ovh
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            mal.api.client:
                base_uri: '%anime.mal.url%'
                headers:
                    X-MAL-CLIENT-ID: '%anime.mal.client_id%'
            aw.client:
                base_uri: '%anime.aw.url%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file