hoyoverse:
    tasks:
        hoyolab_check_in:
            cron: '0 20 * * *'
        hoyolab_missed_check_in:
            cron: '0 14 * * *'
        code_redeem:
            cron: '*/15 * * * *'
        stamina:
            cron: '*/30 * * * *'
        expedition:
            cron: '*/30 * * * *'
        realm_currency:
            cron: '0 * * * *'
        shop_status:
            cron: '0 * * * *'
        mimo:
            cron: '0 */6 * * *'
            jitter: 3
        hilichurl:
            cron: '0 11 * * *'
            jitter: 3
        howl_scratch_card:
            cron: '0 21 * * *'
        dailies_reminder:
            cron: '0 21 * * *'
        weeklies_reminder:
            cron: '0 21 * * 0'
        update_cookie:
            cron: '0 3 * * *'