# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    # configure webp
    webp:
        generate: true
    # configure resolvers
    resolvers:
        # setup the default resolver
        default:
            # use the default web path
            web_path: ~
    # your filter sets are defined here
    filter_sets:
        # use the default cache configuration
        cache: ~
        # the name of the "filter set"
        books_thumb:
            # adjust the image quality
            format: webp
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [300, 450]
                    mode: inset
                    allow_upscale: false
        books_cover:
            # adjust the image quality
            format: webp
            quality: 80
            # list of transformations to apply (the "filters")
            filters:
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [600, 900]
                    mode: inset
                    allow_upscale: false
    loaders:
        default:
            filesystem:
                data_root: '%env(BOOKS_COVERS_FOLDER)%'