passwords:
    domain_name: 'passwords.%domain_name%'
    encryption_key: '%env(PASSWORDS_ENCRYPTION_KEY)%'

twig:
    globals:
        passwords_domain_name: '%passwords.domain_name%'

security:
    role_hierarchy:
        ROLE_ADMIN_PASSWORDS: [ROLE_USER_PASSWORDS]