passwords:
    domain_name: 'passwords.%domain_name%'
    encryption_key: '%env(PASSWORDS_ENCRYPTION_KEY)%'

twig:
    globals:
        passwords_domain_name: '%passwords.domain_name%'

doctrine:
    orm:
        mappings:
            App\PasswordsBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/PasswordsBundle/src/Entity'
                prefix: 'App\PasswordsBundle\Entity'
                alias: PasswordsBundle

security:
    role_hierarchy:
        ROLE_ADMIN_PASSWORDS: [ROLE_USER_PASSWORDS]