videos:
    domain_name: 'videos.%domain_name%'
    base_folder: '%env(VIDEOS_BASE_FOLDER)%'

twig:
    globals:
        videos_domain_name: '%videos.domain_name%'

security:
    role_hierarchy:
        ROLE_ADMIN_VIDEOS: [ROLE_USER_VIDEOS]