videos:
    domain_name: 'videos.%domain_name%'
    base_folder: '%env(VIDEOS_BASE_FOLDER)%'

twig:
    paths:
        src/VideosBundle/templates: 'VideosBundle'
    globals:
        videos_domain_name: '%videos.domain_name%'
