version: '3.9'

services:
    php-8.3-fpm:
        image: php-8.3-fpm
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - mercure
        networks:
            - backend
    apache-httpd:
        image: apache-httpd
        build:
            context: .
            dockerfile: ./docker/apache/Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - php-8.3-fpm
        networks:
            - backend
    mysql:
        image: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "!ChangeMe!"
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - backend
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            # Uncomment the following line to disable HTTPS
            #SERVER_NAME: ":80"
            MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
            MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
        # Uncomment the following line to enable the development mode
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        volumes:
            - mercure_data:/data
            - mercure_config:/config
        ports:
            - "80:80"
            - "443:443"
        networks:
            - backend
    webpack:
        image: webpack
        working_dir: /app
        build:
            context: .
            dockerfile: ./docker/webpack/Dockerfile
        volumes:
            - ./:/app
            - /app/node_modules

volumes:
    mysql-data:
        name: "website-valdi-mysql"
    mercure_data:
        name: "mercure_data"
    mercure_config:
        name: "mercure_config"

networks:
    backend:
        name: "backend"
        driver: bridge
