doctrine:
    orm:
        mappings:
            App\AnimeBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/AnimeBundle/src/Entity'
                prefix: 'App\AnimeBundle\Entity'
                alias: AnimeBundle
