monolog:
    channels:
        - anime_cache
        - anime_aw_handler
        - anime_episode_downloader

when@prod:
    monolog:
        handlers:
            anime_cache_file:
                type: stream
                path: '%kernel.logs_dir%/anime-cache.log'
                level: debug
                channels: ['anime_cache']
            anime_aw_handler_file:
                type: stream
                path: '%kernel.logs_dir%/anime-aw-handler.log'
                level: debug
                channels: ['anime_aw_handler']
            anime_episode_downloader_file:
                type: stream
                path: '%kernel.logs_dir%/anime-episode-downloader.log'
                level: debug
                channels: ['anime_episode_downloader']
