framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            hoyoverse:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: hoyoverse
            hoyoverse_redeem:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: hoyoverse_redeem