;/etc/supervisor/conf.d/website-node-services.conf
[program:website-node-services]
command=/bin/bash -c 'source /home/YOURUSER/.nvm/nvm.sh && nvm use default && npm run start'
directory=/path/to/your/app/node-services
startsecs=0
autostart=true
autorestart=true
startretries=10
user=YOURUSER
environment=NODE_ENV=production
redirect_stderr=true
stdout_logfile=/path/to/your/app/var/log/%(program_name)s.log