;/etc/supervisor/conf.d/website-scheduler-hoyoverse.conf
[program:website-scheduler-hoyoverse]
command=php bin/console messenger:consume scheduler_hoyoverse -vv --time-limit=86400
directory=/path/to/your/app
startsecs=0
autostart=true
autorestart=true
startretries=10
user=www-data
umask=0002
redirect_stderr=true
stdout_logfile=/path/to/your/app/var/log/%(program_name)s.log