;/etc/supervisor/conf.d/website-messenger-anime-episode-download.conf
[program:website-messenger-anime-episode-download]
command=php bin/console messenger:consume anime_episode_download -vv --limit=1 --time-limit=3600
directory=/path/to/your/app
numprocs=2
startsecs=0
autostart=true
autorestart=true
startretries=10
user=www-data
umask=0002
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=true
stdout_logfile=/path/to/your/app/var/log/%(program_name)s_%(process_num)02d.log