;/etc/supervisor/conf.d/website-node-services
[program:website-node-services]
command=/usr/bin/node server.js
directory=/path/to/your/app
startsecs=0
autostart=true
autorestart=true
startretries=10
user=YOURUSER
environment=NODE_ENV=production
redirect_stderr=true
stdout_logfile=/path/to/your/app/var/log/%(program_name)s.log