controllers:
    resource:
        path: ../src/Controller/
        namespace: App\VideosBundle\Controller
    type: attribute
    name_prefix: videos_
    prefix: /videos

when@prod:
    controllers:
        resource:
            path: ../src/Controller/
            namespace: App\VideosBundle\Controller
        type: attribute
        name_prefix: videos_
        host: videos.valdi.ovh