name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup Node.js 20.x
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    # Installazione delle dipendenze Node.js
    - name: Install Node.js dependencies
      run: npm install

    # Validazione dei file composer.json e composer.lock
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    # Cache delle dipendenze di Composer
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # Installazione delle dipendenze PHP con Composer
    - name: Install PHP dependencies with Composer
      run: composer install --prefer-dist --no-progress

    # Build del progetto con Webpack
    - name: Build Webpack
      run: npm run build
